project_id = "ngwrniwffheoybozpkuf"

[functions.analyze-meal]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.resend-login]
verify_jwt = false

[functions.custom-auth-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.delete-client]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.karim-coach]
verify_jwt = false

[functions.lean-brain-chat]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-renewal-email]
verify_jwt = false

[functions.self-signup]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false
