project_id = "ggqoaycpihmwldetqgec"

[functions.analyze-meal]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.resend-login]
verify_jwt = false

[functions.custom-auth-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.delete-client]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.karim-coach]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false
